name: Testing Apps

on: [push]

jobs:
  make-testing:
    name: Checking application
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: "Installing dependencies"
        run: python3 -m pip install -r requirements.txt
        shell: bash

      - name: Checking format_bed
        run: |
          if ! cmp <(python3 src/format_bed.py data/input.bed) data/output.bed; then
            echo "Incorrect output for python3 src/format_bed.py data/input.bed"
            diff <(python3 src/format_bed.py data/input.bed) data/output.bed
          fi
        shell: bash
