name: Testing Apps

on: [push]

jobs:
  make-testing:
    name: Checking application
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: "Installing dependencies"
        run: python3 -m pip install -r requirements.txt
        shell: bash

      - name: Checking query_bed (query-2)
        run: |
          if ! cmp <(python3 src/query_bed.py data/large.bed data/query-2.txt) data/expected-2.txt; then
            echo "Incorrect output for python3 src/query_bed.py data/large.bed data/query-2.txt"
            diff <(python3 python3 src/query_bed.py data/large.bed data/query-2.txt) data/expected-2.txt
          fi
        shell: bash

      - name: Checking query_bed (query-3)
        run: |
          if ! cmp <(python3 src/query_bed.py data/large.bed data/query-3.txt) data/expected-3.txt; then
            echo "Incorrect output for python3 src/query_bed.py data/large.bed data/query-3.txt"
            diff <(python3 python3 src/query_bed.py data/large.bed data/query-3.txt) data/expected-3.txt
          fi
        shell: bash
